udemy:
  email: "rituraj.raj98@gmail.com" # Enter your Udemy registered email here
  password: "Rituraj@1996" # Enter your Udemy password here
  zipcode: "12345" # If Udemy requires a zipcode for your country, enter it here.
  languages: ["English"] # If you want to limit the languages of courses to claim e.g ["French", "Spanish"]
  categories: ["Programming Languages"] # Enter the specific category you want to enroll in, e.g. ["Python","Data Handling"] 